kind: Service
apiVersion: v1
metadata:
  name: fillaripolleri-server
spec:
  selector:
    app: fillaripolleri-server
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      name: fp-server-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fillaripolleri-server
spec:
  selector:
    matchLabels:
      app: fillaripolleri-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fillaripolleri-server
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: fillaripolleri-server
          image: registry.gitlab.com/rainevi/fillaripolleri/server:25c708edb48e311f0bba1b1bd85d588c4e5e5661
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fillaripolleri
                  key: database_url
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: fillaripolleri-client
spec:
  selector:
    app: fillaripolleri-client
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: fp-client-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fillaripolleri-client
spec:
  selector:
    matchLabels:
      app: fillaripolleri-client
  replicas: 1
  template:
    metadata:
      labels:
        app: fillaripolleri-client
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: fillaripolleri-client
          image: registry.gitlab.com/rainevi/fillaripolleri/client:72ff1176d5c56959085a1e66359f3a585066e7cf
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fillaripolleri
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  tls:
    - hosts:
        - raine.cool
      secretName: fillaripolleri-service-tls
  rules:
  - host: raine.cool
    http:
      paths:
      - path: /fillaripolleri
        backend:
          serviceName: fillaripolleri-client
          servicePort: fp-client-port
      - path: /fillaripolleri/api
        backend:
          serviceName: fillaripolleri-server
          servicePort: fp-server-port
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fillaritori-scraper
spec:
  suspend: False
  schedule: "*/10 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: gitlab-registry
          containers:
            - name: fillaritori-scraper
              imagePullPolicy: Always
              image: registry.gitlab.com/rainevi/fillaritori-scraper:50fc79a488ada5313c57a027bb4f488056854306
              args:
                - /bin/sh
                - -c
                - node dist/main.js && curl -fsS --retry 3 https://hc-ping.com/f42ff977-67be-45ce-9708-e8d92836ba56
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: fillaripolleri
                      key: database_url
          restartPolicy: OnFailure
