apiVersion: v1
kind: Secret
metadata:
  name: fillaripolleri
type: Opaque
data:
  database_url: SECRET
  aws_access_key_id: SECRET
  aws_secret_access_key: SECRET
  db_backup_healthcheck_url: SECRET
  db_backup_s3_bucket_url: SECRET
