apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pv-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: torchbox.com/hostpath
parameters:
  pvDir: /mnt/volume-hel1-1
