{{- $fullName := printf "%s-%s" (include "fillaripolleri.fullname" .) "server" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $fullName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $fullName }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: {{ $fullName }}
          image: {{ .Values.server.repository }}:{{ .Values.server.tag }}
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fillaripolleri
                  key: database_url
            - name: PORT
              value: "{{ .Values.server.port }}"
          ports:
            - containerPort: {{ .Values.server.port }}
